baseURL = 'https://leonardoarcari.dev/'
languageCode = 'en-us'
title = "Leo's Pensieve"
theme = 'hugo-coder'

paginate = 20

disqusShortname = "leonardoarcari-dev"

[markup.highlight]
style = "github-dark"

[params]
author = "Leonardo Arcari"
info = "Senior Software Engineer - Finance"
description = "Leonardo Arcari's personal website"
keywords = "blog,developer,personal"
avatarurl = "images/profile-pic.jpg"
#gravatar = "john.doe@example.com"

#faviconSVG = "/img/favicon.svg"
#favicon_32 = "/img/favicon-32x32.png"
#favicon_16 = "/img/favicon-16x16.png"

# since = 2023

math = true
enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/leonardoarcari/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/leonardoarcari/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/arcari_leonardo/"

[[params.social]]
name = "Youtube"
icon = "fa fa-2x fa-youtube-play"
weight = 3
url = "https://youtube.com/@leonardoarcari"

[[params.social]]
name = "Telegram"
icon = "fa fa-2x fa-telegram"
weight = 3
url = "https://t.me/leonardoarcari"

# i18n
[languages.en]
languageName = ":us:"

[languages.it]
languageName = ":it:"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[menu.main]]
name = "About"
weight = 2
url = "about/"
